### ISSUE TITLE
初始化

### ISSUE THREAD

**Issue by luckxs2008** [ttSamoyed/Sand-Riverside#1]
你好 在本地运行项目后 接口调用失败

**Comment by ttSamoyed** [comment]
非纯前端项目，后端仓库见https://github.com/4ever-xxxl/ShaForum_backend.git

**Comment by luckxs2008** [comment]
> 非纯前端项目，后端仓库见https://github.com/4ever-xxxl/ShaForum_backend.git

后端连接404了

**Comment by ttSamoyed** [comment]
项目已完结 后端服务器已关闭 若要使用 需自行部署后端后，修改dataservice实现

**Comment by luckxs2008** [comment]
> 项目已完结 后端服务器已关闭 若要使用 需自行部署后端后，修改dataservice实现

好的。 后端项目的代码仓库连接404，就是你贴的这个 https://github.com/4ever-xxxl/ShaForum_backend.git

**Comment by ttSamoyed** [comment]
抱歉 后端仓库被设置为私人 如需要请联系后端仓库所有者
